import {describe,it,expect,afterEach,vi} from 'vitest';
import {renderToStaticMarkup} from 'react-dom/server';
import {siteSchema,sectionSchema,safeLink,internalLinkErrors,repairGeneratedLinks,newProjectSchema,effectivePageCount} from '@/lib/validation/site';
import {starterSite,demoBrief,newSection} from '@/lib/templates/starter';
import {sectionRegistry,resolveVariant,variants} from '@/lib/templates/registry';
import {checkGeneratedCopy,protectFacts,validateEvidence} from '@/lib/generation/facts';
import {contrast,ensureContrast} from '@/lib/templates/themes';
import {safeJsonLd,structuredData,metadataFor,sitemap} from '@/lib/seo';
import {PlaceholderProvider,providerOrder} from '@/lib/images';
import {SiteRenderer} from '@/components/site/renderer';
import {generateBusinessIdentity} from '@/lib/generation/identity';
import {chooseSuggestedPlace} from '@/lib/google/places';
import {OpenAIProvider} from '@/lib/ai/openai';
import {requiredPageSpecs,isRequiredPageSlug} from '@/lib/generation/required-pages';
const previous=process.env.MOCK_AI;
afterEach(()=>{process.env.MOCK_AI=previous;});
describe('validated component configuration',()=>{
 it('adds the four required pages beyond the requested main-page count',()=>{expect(effectivePageCount('Landing page',1)).toBe(1);expect(effectivePageCount('Landing page',2)).toBe(1);expect(effectivePageCount('Standard',2)).toBe(2);expect(starterSite({...demoBrief,size:'Landing page',pageCount:2}).pages.map(page=>page.slug)).toEqual(['/',...requiredPageSpecs.map(page=>page.slug)]);expect(starterSite({...demoBrief,size:'Standard',pageCount:2}).pages.map(page=>page.slug)).toEqual(['/','/contact',...requiredPageSpecs.map(page=>page.slug)]);});
 it('renders required pages in the footer and links the contact form to privacy',()=>{const site=starterSite({...demoBrief,size:'Landing page',pageCount:1});const html=renderToStaticMarkup(<SiteRenderer site={site} page={site.pages[0]}/>);for(const {slug,title} of requiredPageSpecs){expect(html).toContain(`href="${slug}"`);expect(html).toContain(title);}expect(html).toContain('Read the Privacy Policy');expect(site.pages.filter(page=>isRequiredPageSlug(page.slug))).toHaveLength(4);});
 it('accepts the complete example and rejects unknown or mismatched code',()=>{const site=starterSite(demoBrief);expect(siteSchema.safeParse(site).success).toBe(true);expect(sectionSchema.safeParse({...site.pages[0].sections[0],variant:'<script>alert(1)</script>'}).success).toBe(false);expect(sectionSchema.safeParse({...site.pages[0].sections[0],variant:'services-list'}).success).toBe(false);expect(()=>resolveVariant('arbitrary-component')).toThrow();});
 it('registers the required number of distinct variants',()=>{expect(variants.hero).toHaveLength(8);expect(variants.services).toHaveLength(10);expect(Object.keys(sectionRegistry).length).toBe(100);});
 it('rejects duplicate routes and unsafe CTA links',()=>{const site=starterSite(demoBrief);site.pages[1].slug='/';expect(siteSchema.safeParse(site).success).toBe(false);for(const link of ['javascript:alert(1)','//evil.example','data:text/html,hello'])expect(safeLink.safeParse(link).success).toBe(false);});
 it('finds missing page and section destinations and repairs generated links',()=>{const site=starterSite(demoBrief);site.pages[0].sections[0].href='/missing';site.pages[1].sections[0].href='#missing';expect(internalLinkErrors(site)).toHaveLength(2);repairGeneratedLinks(site);expect(internalLinkErrors(site)).toEqual([]);});
 it('renders user input as text instead of executing it',()=>{const site=starterSite(demoBrief);site.pages[0].sections[0].title='<script>alert(1)</script>';const html=renderToStaticMarkup(<SiteRenderer site={site} page={site.pages[0]}/>);expect(html).toContain('&lt;script&gt;');expect(html).not.toContain('<script>alert');});
});
describe('fact safety',()=>{
 it('uses the phone from the same Google Places result as the suggested address',()=>{const place=chooseSuggestedPlace([{formattedAddress:'1 Example Street, Manchester, United Kingdom',internationalPhoneNumber:'+44 161 555 0123',addressComponents:[{longText:'Manchester',types:['locality']},{longText:'United Kingdom',types:['country']}]}],'United Kingdom');expect(place).toEqual({address:'1 Example Street, Manchester, United Kingdom',city:'Manchester',country:'United Kingdom',phone:'+44 161 555 0123'});});
 it('suggests industry-specific draft details without an external provider in demo mode',async()=>{const placesKey=process.env.GOOGLE_PLACES_API_KEY;process.env.GOOGLE_PLACES_API_KEY='';process.env.MOCK_AI='true';try{const result=await generateBusinessIdentity({...demoBrief,name:'New business website',autoGenerate:true,addressVerified:false},'test');expect(result.brief.name).toContain('Gaming lounge');expect(result.brief.services.length).toBeGreaterThanOrEqual(3);expect(result.brief.description).toContain(result.brief.services[0]);expect(['bold','playful','friendly']).toContain(result.brief.tone);expect(result.brief.style).toBe('Gaming');expect(result.brief.primary).toMatch(/^#[0-9a-fA-F]{6}$/);expect(result.brief.city).not.toBe('Location pending');expect(result.brief.email).toMatch(/^hello@[a-z0-9-]+\.example$/);expect(result.brief.emailVerified).toBe(false);expect(result.brief.address).toBe('');}finally{if(placesKey===undefined)delete process.env.GOOGLE_PLACES_API_KEY;else process.env.GOOGLE_PLACES_API_KEY=placesKey;}});
 it('keeps suggested contact details private until the owner confirms them',()=>{const input=newProjectSchema.parse({category:'Gaming lounge',country:'United Kingdom'});for(const key of ['name','city','services','tone','email','phone','style','primary','dark','imageStrategy','instructions'])expect(input).not.toHaveProperty(key);const draft=starterSite({...demoBrief,autoGenerate:true,address:'1 Example Street, Manchester',addressVerified:false,phone:'+44 1234 567890',phoneVerified:false,email:'hello@sample.example',emailVerified:false});expect(draft.business.facts.address).toBeUndefined();expect(draft.business.facts.phone).toBeUndefined();expect(draft.business.facts.email).toBeUndefined();const html=renderToStaticMarkup(<SiteRenderer site={draft} page={draft.pages.find(p=>p.slug==='/contact')!}/>);expect(html).not.toContain('1 Example Street');expect(html).not.toContain('+44 1234 567890');expect(html).not.toContain('hello@sample.example');});
 it('preserves authoritative facts against model changes',()=>{const original=starterSite(demoBrief).business;original.facts.phone={value:'+44 1234',classification:'VERIFIED',source:'independent confirmation'};const changed=structuredClone(original);changed.name='Fake';changed.facts.phone.value='Invented';expect(protectFacts(original,changed)).toEqual(original);});
 it('rejects unsupported testimonials and statistics',()=>{const business=starterSite(demoBrief).business;const section=newSection('testimonials');section.items=[{title:'Fake customer',text:'Wonderful!',factRef:'missing',image:'',href:''}];expect(()=>validateEvidence(section,business)).toThrow();const hero=newSection('hero');hero.body='We have 5000 customers and 20 years of experience.';expect(()=>checkGeneratedCopy(hero,business)).toThrow();});
 it('accepts only exact user-supplied evidence',()=>{const site=starterSite({...demoBrief,testimonials:[{name:'Real supplied customer',quote:'A supplied quote.'}]});const testimonial=site.pages[0].sections.find(s=>s.type==='testimonials')!;expect(()=>validateEvidence(testimonial,site.business)).not.toThrow();testimonial.items[0].text='Invented quote';expect(()=>validateEvidence(testimonial,site.business)).toThrow();});
});
describe('SEO and design safety',()=>{
 it('builds a valid automatic theme in demo mode',async()=>{process.env.MOCK_AI='true';const site=starterSite(demoBrief);const designed=await new OpenAIProvider('test').generateDesign(site,demoBrief);expect(siteSchema.safeParse(designed).success).toBe(true);expect(contrast(designed.theme.background,designed.theme.foreground)).toBeGreaterThanOrEqual(4.5);});
 it('applies AI generated colors and layout in live mode',async()=>{process.env.MOCK_AI='false';const site=starterSite(demoBrief);const provider=new OpenAIProvider('test');const structured=vi.spyOn(provider,'structured').mockResolvedValue({theme:{...site.theme,primary:'#dabcff',foreground:'#eeeeee'},navigation:'centered',footer:'minimal'});try{const designed=await provider.generateDesign(site,demoBrief);expect(structured).toHaveBeenCalledOnce();expect(designed.navigation).toBe('centered');expect(designed.footer).toBe('minimal');expect(designed.theme.primary).toBe('#dabcff');expect(contrast(designed.theme.background,designed.theme.foreground)).toBeGreaterThanOrEqual(4.5);}finally{structured.mockRestore();}});
 it('plans only main pages while preserving required routes',async()=>{process.env.MOCK_AI='false';const site=starterSite({...demoBrief,size:'Landing page',pageCount:1});const provider=new OpenAIProvider('test');const structured=vi.spyOn(provider,'structured').mockResolvedValue({strategy:'Direct enquiries',pages:[{title:'Home',slug:'/',objective:'Introduce the business',variants:['hero-centered','contact-centered']} ]});try{const planned=await provider.planWebsite(site,{...demoBrief,size:'Landing page',pageCount:1});expect(planned.pages.map(page=>page.slug)).toEqual(site.pages.map(page=>page.slug));expect(structured.mock.calls[0][2]).toMatchObject({requestedPageCount:1});}finally{structured.mockRestore();}});
 it('uses the dedicated AI writer for required pages and keeps the review notice',async()=>{process.env.MOCK_AI='false';const site=starterSite(demoBrief);const page=site.pages.find(page=>page.slug==='/privacy-policy')!;const provider=new OpenAIProvider('test');const structured=vi.spyOn(provider,'structured').mockResolvedValue({intro:'Please review these privacy details.',items:page.sections[0].items.map(item=>({title:item.title,text:item.text})),seo:page.seo});try{const written=await provider.generatePage(site,page,demoBrief);expect(structured).toHaveBeenCalledOnce();expect(written.sections[0].body).toContain('Draft policy — review and complete before publishing.');expect(written.sections[0].body).toContain('Please review these privacy details.');expect(written.slug).toBe('/privacy-policy');}finally{structured.mockRestore();}});
 it('escapes JSON-LD and XML and includes owner supplied business facts without invented ratings',()=>{expect(safeJsonLd({text:'</script>'})).not.toContain('</script>');const site=starterSite(demoBrief);const data=structuredData(site,site.pages[0],'https://example.com');expect(JSON.stringify(data)).toContain('NovaForge Esports');expect(JSON.stringify(data)).not.toContain('aggregateRating');expect(metadataFor(site,site.pages[1],'https://example.com').alternates.canonical).toBe('https://example.com/services');expect(sitemap(site,'https://example.com')).toContain('<loc>https://example.com/</loc>');});
 it('repairs insufficient text contrast',()=>{const theme=starterSite(demoBrief).theme;const safe=ensureContrast({...theme,background:'#ffffff',foreground:'#eeeeee',muted:'#dddddd'});expect(contrast(safe.background,safe.foreground)).toBeGreaterThanOrEqual(4.5);expect(contrast(safe.background,safe.muted)).toBeGreaterThanOrEqual(4.5);});
});
describe('image abstraction',()=>{
 it('avoids paid providers in demo mode and uses a designed fallback',async()=>{process.env.MOCK_AI='true';expect(providerOrder('mixed').map(x=>x.name)).toEqual(['placeholder']);const image=await new PlaceholderProvider().generateImage({projectId:'test',intent:'Gaming interior',query:'gaming',style:'Gaming',orientation:'landscape'});expect(image.bytes!.length).toBeGreaterThan(500);expect(image.provider).toBe('placeholder');});
 it('honors explicit stock-only and AI-only strategies',()=>{process.env.MOCK_AI='false';expect(providerOrder('pexels').map(x=>x.name)).toEqual(['pexels','placeholder']);expect(providerOrder('gpt-image-2').map(x=>x.name)).toEqual(['gpt-image-2','placeholder']);});
 it('puts portable imagery after owner uploads for the Google strategy',()=>{process.env.MOCK_AI='false';expect(providerOrder('google').map(x=>x.name)).toEqual(['gpt-image-2','pexels','comfyui','placeholder']);});
});
