"use client";
import {useEffect,useState} from 'react';
import {Plus,Search,ArrowUpRight,MoreHorizontal,Globe,Layers3,Clock3,Sparkles,Copy,Trash2,Download,Eye} from 'lucide-react';
import {Shell} from './shell';
import {Wizard} from './generator/wizard';
import {api} from '@/lib/client';
import {Brief} from '@/lib/validation/site';
import {demoBrief} from '@/lib/templates/starter';
type Project={id:string;name:string;status:string;brief:Brief;createdAt:string;version:number};
export function Dashboard({name,mock}:{name:string;mock:boolean}){
 const[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[wizard,setWizard]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('All websites'),[creating,setCreating]=useState(false);
 const refresh=()=>api<Project[]>('/api/projects').then(setProjects).catch(e=>setError(e.message)).finally(()=>setLoading(false));
 useEffect(()=>{void refresh();if(new URLSearchParams(window.location.search).has('new'))setWizard(true);const interval=setInterval(refresh,10000);return()=>clearInterval(interval);},[]);
 const visible=projects.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())&&(filter==='All websites'||(filter==='Ready'?p.status==='READY':p.status!=='READY')));
 async function action(p:Project,kind:string){try{if(kind==='delete'){if(!window.confirm(`Delete ${p.name} and its saved versions?`))return;await api('/api/projects/'+p.id,{method:'DELETE'});}else await api('/api/projects/'+p.id+'/'+kind,{method:'POST',body:'{}'});await refresh();}catch(e){setError(e instanceof Error?e.message:'Action failed');}}
 return <Shell name={name} onNew={()=>setWizard(true)}><main className="dashboard"><div className="page-heading"><div><p className="eyebrow">YOUR CREATIVE WORKSPACE</p><h1>Good ideas deserve<br className="mobile-only"/> great websites<span>.</span></h1><p>From the first spark to the final detail. Make it yours.</p></div><button className="button primary" onClick={()=>setWizard(true)}><Plus size={17}/>New website</button></div>
 <section className="dashboard-banner"><div><div className="banner-label"><span/>YOUR NEXT BIG THING STARTS HERE</div><h2>A business brief.<br/>A whole new possibility.</h2><p>Bring your business to life with a website<br className="desktop-only"/> that’s built around you.</p><button onClick={()=>setWizard(true)} className="button dark">Let’s create something <ArrowUpRight size={16}/></button></div><div className="banner-art" aria-hidden="true"><div className="floating-card card-back"><div/><span/><span/></div><div className="floating-card card-front"><div className="mini-nav"><i/><span/><span/></div><div className="mini-hero"><div><span/><span/><span/><i/></div><div className="mini-orb"/></div><div className="mini-tiles"><i/><i/><i/></div></div><span className="art-spark">✳</span><span className="art-cursor">↖ <small>Your next website</small></span><span className="art-dot"/></div></section>
 <div className="workspace-stats"><div><span className="stat-icon"><Globe size={18}/></span><span><strong>{projects.length}</strong><small>Total websites</small></span></div><div><span className="stat-icon green"><Layers3 size={18}/></span><span><strong>{projects.filter(p=>p.status==='READY').length}</strong><small>Ready to share</small></span></div><div><span className="stat-icon peach"><Clock3 size={18}/></span><span><strong>{projects.filter(p=>p.status!=='READY').length}</strong><small>In the making</small></span></div><div className="mode-stat"><span className="status-dot"/>{mock?'Demo mode · no API credits needed':'Live generation enabled'}</div></div>
 <div className="projects-heading"><h2>Your websites <span>{projects.length}</span></h2><div className="search-field"><Search size={16}/><input aria-label="Search websites" placeholder="Search websites…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="project-filters">{['All websites','Ready','In progress'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}<span>Made by you. Built for what’s next.</span></div>
 {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {loading?<div className="project-grid">{[1,2,3].map(n=><div className="project-skeleton" key={n}/>)}</div>:<div className="project-grid">{visible.map(p=><article key={p.id} className="project-card"><a className="project-thumbnail" href={'/projects/'+p.id}>{p.status==='READY'?<iframe title={'Saved homepage of '+p.name} src={'/preview/'+p.id} loading="lazy" tabIndex={-1} aria-hidden="true"/>:<div className="thumbnail-pending"><Globe size={32}/><strong>{p.name}</strong><small>{p.status==='FAILED'?'Generation needs attention':'Website in progress'}</small></div>}<span className="thumbnail-open">Open editor <ArrowUpRight size={15}/></span></a><div className="project-info"><div><h3><a href={'/projects/'+p.id}>{p.name}</a></h3><p>{p.brief.category} <span>·</span> {p.brief.city}</p></div><details className="project-menu"><summary aria-label={'Actions for '+p.name}><MoreHorizontal size={21}/></summary><div><a href={'/preview/'+p.id} target="_blank"><Eye size={15}/>Preview</a><button onClick={()=>action(p,'duplicate')}><Copy size={15}/>Duplicate</button>{p.status==='READY'&&<a href={'/api/projects/'+p.id+'/export'}><Download size={15}/>Export</a>}<button className="danger" onClick={()=>action(p,'delete')}><Trash2 size={15}/>Delete</button></div></details></div><div className="project-meta"><span className={'badge '+(p.status==='READY'?'ready':p.status==='FAILED'?'failed':'')}><i/>{p.status==='READY'?'Ready':p.status==='FAILED'?'Needs attention':'In progress'}</span><span>{new Date(p.createdAt).toLocaleDateString('en',{month:'short',day:'numeric'})}</span></div></article>)}<button className="new-project-card" onClick={()=>setWizard(true)}><span><Plus size={24}/></span><strong>A fresh start</strong><p>Your next idea belongs here.</p><small>Create a website <ArrowUpRight size={14}/></small></button></div>}
 {!loading&&!projects.length&&<div className="demo-invite"><Sparkles size={20}/><div><strong>Want to take a look around first?</strong><p>Create the NovaForge demo and explore a complete website.</p></div><button className="button secondary" disabled={creating} onClick={async()=>{setCreating(true);try{const p=await api<{id:string}>('/api/projects',{method:'POST',body:JSON.stringify(demoBrief)});window.location.href='/projects/'+p.id;}catch(e){setError(e instanceof Error?e.message:'Unable to create demo');setCreating(false);}}}>{creating?'Creating…':'Try the example'}<ArrowUpRight size={15}/></button></div>}
 <footer className="dashboard-footer"><span>Made for your ideas, big and small.</span><span>AXOGEN STUDIO <span>✳</span></span></footer></main>{wizard&&<Wizard onClose={()=>setWizard(false)} onCreated={id=>window.location.href='/projects/'+id}/>}</Shell>;
}
